# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: f2464099016923e3a2e92c820f073e37a09a6932723d2a063d48b1488cfbed5e31177d2a89bbedeed207da7fc5e39cdc778b82c70b4b7809ab8fd11c77d725f5

test:
  domain_name: example.com 
  secret_key_base: bfcbb2c1bbbd374f959612c0aff3057e2da992ab24a2571960eef4017480d5a897f5baed282667078db729dde727f77ce057760fa3ad88cbeea4dbd8e648df2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
